CREATE (khabib:Fighter {name: 'Khabib Nurmagomedov', weight: 155})
CREATE (rafael:Fighter {name: 'Rafael Dos Anjos', weight: 155})
CREATE (neil:Fighter {name: 'Neil Magny', weight: 170})
CREATE (jon:Fighter {name: 'Jon Jones', weight: 205})
CREATE (daniel:Fighter {name: 'Daniel Cormier', weight: 205})
CREATE (michael:Fighter {name: 'Michael Bisping', weight: 185})
CREATE (matt:Fighter {name: 'Matt Hamill', weight: 185})
CREATE (brandon:Fighter {name: 'Brandon Vera', weight: 205})
CREATE (frank:Fighter {name: 'Frank Mir', weight: 230})
CREATE (brock:Fighter {name: 'Brock Lesnar', weight: 230})
CREATE (kelvin:Fighter {name: 'Kelvin Gastelum', weight: 185})

CREATE (khabib)-[:BEAT]->(rafael)
CREATE (rafael)-[:BEAT]->(neil)
CREATE (jon)-[:BEAT]->(daniel)
CREATE (michael)-[:BEAT]->(matt)
CREATE (jon)-[:BEAT]->(brandon)
CREATE (brandon)-[:BEAT]->(frank)
CREATE (frank)-[:BEAT]->(brock)
CREATE (neil)-[:BEAT]->(kelvin)
CREATE (kelvin)-[:BEAT]->(michael)
CREATE (michael)-[:BEAT]->(matt)
CREATE (michael)-[:BEAT]->kelvin)
CREATE (matt)-[:BEAT]->(jon)

MATCH (f1)-[:BEAT]->(f2)
RETURN f1.name, f1.weight, f2.name, f2.weight